[PE1-1505] CDN Class "kind" implementation
gympass/cdn-origin-controller pull request #95
Opened 2023-08-25 17:05 UTC by caiofralmeida

## Description
The idea is avoid to configuring kinds of values to provide different configurations and have a Kubernetes kind giving the hosted zone and certificate for each "class" configured. In this way, the developer should provide only the "class" desired without concern about hosted zones and certificate configurations.

## Motivation and Context
- CDN Ingress interface https://gympass.atlassian.net/browse/PE1-1505

## How has this been tested?
Tested manually via local environment (I'm going to test through pe-develop Kubernetes cluster as well)

## Checklist

- [x] I have implemented automated tests for the changes.
- [x] I have updated the documentation accordingly.

2023-08-25 18:36 UTC, monicajss requested changes

2023-08-25 18:36 UTC, monicajss commented on internal/k8s/cdnclass.go
> +// CDNClass ...
I think you need to continue the text... Right?

2023-08-25 18:36 UTC, monicajss commented on internal/k8s/cdnclass.go
> +	// CertificateArn ...
same here

2023-08-25 18:36 UTC, monicajss commented on internal/k8s/cdnclass.go
> +	// HostedZoneID ...
and here

2023-08-28 10:33 UTC, go-faustino approved these changes
Great work, this is really useful!!!

Left a couple of comments, which can be addressed later, but overall LGTM!

2023-08-29 11:35 UTC, caiofralmeida commented on api/v1alpha1/cdnclass_types.go
> +	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
There is no controller to manage this resource, until then it's just a "store" of the settings, I couldn't think of what information to put in the status unless I create a controller for that, I don't know if it's worth it at this point. What do you think?

2023-08-29 11:46 UTC, caiofralmeida commented on api/v1alpha1/cdnclass_types.go
> +	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
Anyway, I configured the field Conditions to the status:
```go
// CDNClassStatus defines the observed state of CDNClass
type CDNClassStatus struct {
	// CDNClass resource condition
	// +optional
	// +nullable
	Conditions []metav1.Condition `json:"conditions"`
}
```

2023-08-29 11:52 UTC, merged